version: '3.8'
services:
  stats-server:
    build: ./stats
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hits

  ewm-service:
    build: ./ewm
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me
      #- STATS_URL=http://stats-server:9090
      - FEIGN_URL=http://stats-server:9090

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=hits
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test