CREATE TABLE IF NOT EXISTS hits(
    id bigint generated by default as identity primary key,
    app varchar(200),
    uri varchar(2000),
    ip varchar(200),
    timestamp timestamp without time zone
);